[ADDED] Deps again because of class path error
```
 E  FATAL EXCEPTION: main
                                                                                                    Process: dev.hossain.timeline, PID: 19239
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;
                                                                                                    	at dev.hossain.timeline.Parser$parse$4.invokeSuspend(Parser.kt:47)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@f7fb9c, androidx.compose.runtime.BroadcastFrameClock@ee7d9a5, StandaloneCoroutine{Cancelling}@7a6217a, AndroidUiDispatcher@e4b9d2b]
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "okio.Okio" on path: DexPathList[[zip file "/data/app/~~vx1BOyagta2gik24a1WTZg==/dev.hossain.timeline-qPJC9x7Xv7si7CPeKlZLYw==/base.apk"],nativeLibraryDirectories=[/data/app/~~vx1BOyagta2gik24a1WTZg==/dev.hossain.timeline-qPJC9x7Xv7si7CPeKlZLYw==/lib/arm64, /data/app/~~vx1BOyagta2gik24a1WTZg==/dev.hossain.timeline-qPJC9x7Xv7si7CPeKlZLYw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
                                                                                                    	... 9 more
```